In [9]:
import pandas as pd
import openpyxl
import plotly.express as px

In [10]:
#wb = openpyxl.load_workbook('202206_housing.xlsx')
#wb['1.매매종합']

In [11]:
import xlwings as xw 

path = '202206_housing.xlsx'
wb = xw.Book(path)
sheet = wb.sheets['1.매매종합']

# row_num = 442
# data_range = 'A2:GE' + str(row_num)
# raw_data = sheet[data_range].options(pd.DataFrame, index=False, header=True).value

row_num = sheet.range(1,1).end('down').end('down').end('down').row  
data_range = 'A2:GE' + str(row_num)
raw_data = sheet[data_range].options(pd.DataFrame, index=False, header=True).value

In [12]:
#print(raw_data)

In [13]:
big_col = list(raw_data.columns)
small_col = list(raw_data.iloc[0])

In [14]:
bignames = '서울 대구 부산 대전 광주 인천 울산 세종 경기 강원 충북 충남 전북 전남 경북 경남 제주도 6개광역시 5개광역시 수도권 기타지방 구분 전국'
bigname_list = bignames.split(' ')
big_col = list(raw_data.columns)
small_col = list(raw_data.iloc[0])

for num, gu_data in enumerate(small_col):
    if gu_data == None:
        small_col[num] = big_col[num]
    
    check = num
    while True:
        if big_col[check] in bigname_list:
            big_col[num] = big_col[check]
            break
        else:
            check = check - 1
            
big_col[129] = '경기' 
big_col[130] = '경기'
small_col[185] = '서귀포'

raw_data.columns = [big_col, small_col]
print(raw_data)
new_col_data = raw_data.drop([0,1])
print(f'\n{new_col_data}')

                 구분          전국          서울                              \
                 구분          전국          서울        강북\n14개구         강북구
0              None        None        None            None         강북구
1    Classification       Total       Seoul  Northern seoul  Gangbuk-gu
2              86.1    27.68215   23.472864       32.594416        None
3               2.0    27.68215   23.472864       32.554907        None
4               3.0   27.723591   23.440488       32.554907        None
..              ...         ...         ...             ...         ...
435             2.0  100.207368  100.196351      100.249743  100.044046
436             3.0  100.305605  100.252724      100.278068  100.045391
437             4.0  100.516504  100.379697      100.346183  100.079498
438             5.0  100.768293  100.557572      100.514011  100.107569
439             6.0  100.868527  100.723141      100.673584  100.170506

                                                                     ...  \
             광진구         노원구         도봉구           동대문구         마포구  ...
0            광진구         노원구         도봉구           동대문구         마포구  ...
1    Gwangjin-gu    Nowon-gu   Dobong-gu  Dongdaemun-gu     Mapo-gu  ...
2           None        None        None           None        None  ...
3           None        None        None           None        None  ...
4           None        None        None           None        None  ...
..           ...         ...         ...            ...         ...  ...
435    100.39913  100.045036  100.454603      99.992477  100.038371  ...
436   100.426325  100.040477  100.573273      99.956221  100.070985  ...
437   100.736142  100.054681  100.662162     100.063984  100.105513  ...
438    101.29182  100.025793  100.833792     100.220039  100.240308  ...
439   101.431506   99.931069  100.927532     100.279169  100.498788  ...

             경남                                                      \
            의창구         진해구       양산     거제          진주          김해
0           의창구         진해구     None   None        None        None
1       Uichang      Jinhae  Yangsan  Geoje       Jinju      Gimhae
2          None        None     None   None        None        None
3          None        None     None   None        None        None
4          None        None     None   None        None        None
..          ...         ...      ...    ...         ...         ...
435  100.287111  100.317359     None   None  100.502209  100.183431
436  100.425939  100.501761     None   None  101.072266  100.148233
437  100.854237  101.201873     None   None  101.461046  100.124852
438   101.60097  102.027125     None   None  102.017169  100.116237
439  102.668235  102.383504     None   None  102.557368  100.108882

                     제주도                                    기타지방
            통영       제주도              서귀포                   기타지방
0         None      None             None                   None
1    Tongyoung  Jeju-do   Jeju/\nSeogwipo  Non-Metropolitan Area
2         None      None             None                   None
3         None      None             None                   None
4         None      None             None                   None
..         ...       ...              ...                    ...
435       None      None        100.28025             100.308473
436       None      None       100.403816             100.536559
437       None      None        100.55995             100.874314
438       None      None       100.949068             101.267352
439       None      None       101.229909             101.491416

[440 rows x 187 columns]

       구분          전국          서울                                      \
       구분          전국          서울    강북\n14개구         강북구         광진구
2    86.1    27.68215   23.472864   32.594416        None        None
3     2.0    27.68215   23.472864   32.554907        None        None
4     3.0   27.723591   23.440488   32.554907        None        None
5     4.0   27.516389   23.310982   32.436382        None        None
6     5.0   27.392068   23.116724   32.080807        None        None
..    ...         ...         ...         ...         ...         ...
435   2.0  100.207368  100.196351  100.249743  100.044046   100.39913
436   3.0  100.305605  100.252724  100.278068  100.045391  100.426325
437   4.0  100.516504  100.379697  100.346183  100.079498  100.736142
438   5.0  100.768293  100.557572  100.514011  100.107569   101.29182
439   6.0  100.868527  100.723141  100.673584  100.170506  101.431506

                                                     ...          경남  \
            노원구         도봉구        동대문구         마포구  ...         의창구
2          None        None        None        None  ...        None
3          None        None        None        None  ...        None
4          None        None        None        None  ...        None
5          None        None        None        None  ...        None
6          None        None        None        None  ...        None
..          ...         ...         ...         ...  ...         ...
435  100.045036  100.454603   99.992477  100.038371  ...  100.287111
436  100.040477  100.573273   99.956221  100.070985  ...  100.425939
437  100.054681  100.662162  100.063984  100.105513  ...  100.854237
438  100.025793  100.833792  100.220039  100.240308  ...   101.60097
439   99.931069  100.927532  100.279169  100.498788  ...  102.668235

                                                            제주도              \
            진해구    양산    거제          진주          김해    통영   제주도         서귀포
2          None  None  None        None        None  None  None        None
3          None  None  None        None        None  None  None        None
4          None  None  None        None        None  None  None        None
5          None  None  None        None        None  None  None        None
6          None  None  None        None        None  None  None        None
..          ...   ...   ...         ...         ...   ...   ...         ...
435  100.317359  None  None  100.502209  100.183431  None  None   100.28025
436  100.501761  None  None  101.072266  100.148233  None  None  100.403816
437  101.201873  None  None  101.461046  100.124852  None  None   100.55995
438  102.027125  None  None  102.017169  100.116237  None  None  100.949068
439  102.383504  None  None  102.557368  100.108882  None  None  101.229909

           기타지방
           기타지방
2          None
3          None
4          None
5          None
6          None
..          ...
435  100.308473
436  100.536559
437  100.874314
438  101.267352
439  101.491416

[438 rows x 187 columns]

In [32]:
# [예제 2.9] 인덱스를 위한 날짜 리스트 만들기 

index_list = list(new_col_data['구분']['구분'])

new_index = []

for num, raw_index in enumerate(index_list):
    temp = str(raw_index).split('.')
    if int(temp[0]) > 12 :
        if len(temp[0]) == 2:
            new_index.append('19' + temp[0] + '.' + temp[1])
        else:
            new_index.append(temp[0] + '.' + temp[1])
    else:
        new_index.append(new_index[num-1].split('.')[0] + '.' + temp[0])

        
# [예제 2.10] 만들어진 날짜 리스트를 인덱스로 설정 

new_col_data.set_index(pd.to_datetime(new_index), inplace=True)
cleaned_data  = new_col_data.drop(('구분', '구분'), axis=1)

jungug = cleaned_data['전국']
#jungug.to_excel('전국.xlsx')

print(jungug['전국'])
#px.line(cleaned_data)

1986-01-01      27.68215
1986-02-01      27.68215
1986-03-01     27.723591
1986-04-01     27.516389
1986-05-01     27.392068
                 ...
2022-02-01    100.207368
2022-03-01    100.305605
2022-04-01    100.516504
2022-05-01    100.768293
2022-06-01    100.868527
Name: 전국, Length: 438, dtype: object

1986-01-01      27.68215
1986-02-01      27.68215
1986-03-01     27.723591
1986-04-01     27.516389
1986-05-01     27.392068
                 ...
2022-02-01    100.207368
2022-03-01    100.305605
2022-04-01    100.516504
2022-05-01    100.768293
2022-06-01    100.868527
Name: 전국, Length: 438, dtype: object